# permissions for end users to view backuprestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: backuprestore-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: backuprestore-operator
    app.kubernetes.io/part-of: backuprestore-operator
    app.kubernetes.io/managed-by: kustomize
  name: backuprestore-viewer-role
rules:
- apiGroups:
  - batch.backuprestore.geoffrey.io
  resources:
  - backuprestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.backuprestore.geoffrey.io
  resources:
  - backuprestores/status
  verbs:
  - get
