---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch.backuprestore.geoffrey.io
  resources:
  - backuprestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.backuprestore.geoffrey.io
  resources:
  - backuprestores/finalizers
  verbs:
  - update
- apiGroups:
  - batch.backuprestore.geoffrey.io
  resources:
  - backuprestores/status
  verbs:
  - get
  - patch
  - update
