apiVersion: batch.backuprestore.geoffrey.io/v1alpha1
kind: BackupRestore
metadata:
  labels:
    app.kubernetes.io/name: backuprestore
    app.kubernetes.io/instance: backuprestore-sample
    app.kubernetes.io/part-of: backuprestore-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: backuprestore-operator
  name: backuprestore-sample
spec:
  # TODO(user): Add fields here
